---

- name: set host
  hosts: localhost
  vars:
    password_store: ~/.password-store
    fish_configuration_dir: ~/.config/fish
  tasks:

  - name: install packages
    become: yes
    package:
      name:
        - neovim
        - git-all
        - fzf
        - pass
        - fish
        - tmux
      state: present

  - name: clone password store
    command: "git clone git@bitbucket.org:ficoos/pass-store.git {{ password_store }}"
    args:
      creates: "{{ password_store }}"

  - name: configure tmux
    copy:
      src: tmux.conf
      dest: ~/.tmux.conf
      mode: 0664

  - name: configure gitignore
    copy:
      src: gitignore
      dest: ~/.gitignore
      mode: 0664

  - name: configure gitconfig
    copy:
      src: gitconfig
      dest: ~/.gitconfig
      mode: 0664

  - name: configure bash
    copy:
      src: bashrc
      dest: ~/.bashrc
      mode: 0664

  - name: create fish configuration dir
    file:
      path: "{{ fish_configuration_dir }}"
      state: directory
      mode: 0700

  - name: configure fish
    copy:
      src: config.fish
      dest: "{{ fish_configuration_dir }}/config.fish"
      mode: 0664

